CREATE TABLE "Currencies" (
	"ID"	INTEGER UNIQUE,
	"Name"	TEXT NOT NULL,
	"Sumbol"	TEXT NOT NULL,
	"OtherNames"	TEXT,
	"IsDefault"	INTEGER NOT NULL DEFAULT 0,
	"IsMainStable"	INTEGER NOT NULL DEFAULT 0,
	"LastExchangeRate"	NUMERIC DEFAULT 0.1,
	PRIMARY KEY("ID" AUTOINCREMENT)
);