CREATE TABLE "Categories" (
	"ID"	INTEGER NOT NULL,
	"ParentID"	INTEGER DEFAULT 0,
	"Name"	TEXT NOT NULL,
	"CreatedBy"	INTEGER NOT NULL DEFAULT 1,
	"CreateDate"	TEXT NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT),
	FOREIGN KEY("ParentID") REFERENCES "Categories"("ID") ON DELETE SET DEFAULT,
	FOREIGN KEY("CreatedBy") REFERENCES "Users"("ID") ON DELETE SET DEFAULT
);