CREATE TABLE "Limits" (
	"ID"	INTEGER NOT NULL DEFAULT 1,
	"StartPeriod"	TEXT NOT NULL,
	"EndPeriod"	TEXT NOT NULL,
	"LimitSumm"	NUMERIC NOT NULL,
	"LimitType"	INTEGER NOT NULL,
	"CreditByLastPeriod"	NUMERIC NOT NULL,
	"Currency"	INTEGER NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT),
	FOREIGN KEY("LimitType") REFERENCES "LimitTypes"("ID") ON DELETE CASCADE,
	FOREIGN KEY("Currency") REFERENCES "Currencies"("ID") ON UPDATE CASCADE
);